/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnUSIndexRouteImport } from './routes/en-US/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as EnUSSplatRouteImport } from './routes/en-US/$'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTanstackFormRouteImport } from './routes/demo/tanstack-form'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiVerifyRecaptchaRouteImport } from './routes/api/verify-recaptcha'
import { Route as LangContactRouteImport } from './routes/$lang/contact'
import { Route as DemoSentryTestingRouteImport } from './routes/demo/sentry.testing'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnUSIndexRoute = EnUSIndexRouteImport.update({
  id: '/en-US/',
  path: '/en-US/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/$lang/',
  path: '/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnUSSplatRoute = EnUSSplatRouteImport.update({
  id: '/en-US/$',
  path: '/en-US/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackFormRoute = DemoTanstackFormRouteImport.update({
  id: '/demo/tanstack-form',
  path: '/demo/tanstack-form',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyRecaptchaRoute = ApiVerifyRecaptchaRouteImport.update({
  id: '/api/verify-recaptcha',
  path: '/api/verify-recaptcha',
  getParentRoute: () => rootRouteImport,
} as any)
const LangContactRoute = LangContactRouteImport.update({
  id: '/$lang/contact',
  path: '/$lang/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoSentryTestingRoute = DemoSentryTestingRouteImport.update({
  id: '/demo/sentry/testing',
  path: '/demo/sentry/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/$lang/contact': typeof LangContactRoute
  '/api/verify-recaptcha': typeof ApiVerifyRecaptchaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-form': typeof DemoTanstackFormRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/en-US/$': typeof EnUSSplatRoute
  '/$lang/': typeof LangIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/en-US/': typeof EnUSIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/$lang/contact': typeof LangContactRoute
  '/api/verify-recaptcha': typeof ApiVerifyRecaptchaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-form': typeof DemoTanstackFormRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/en-US/$': typeof EnUSSplatRoute
  '/$lang': typeof LangIndexRoute
  '/blog': typeof BlogIndexRoute
  '/en-US': typeof EnUSIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/$lang/contact': typeof LangContactRoute
  '/api/verify-recaptcha': typeof ApiVerifyRecaptchaRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-form': typeof DemoTanstackFormRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/en-US/$': typeof EnUSSplatRoute
  '/$lang/': typeof LangIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/en-US/': typeof EnUSIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/demo/sentry/testing': typeof DemoSentryTestingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/$lang/contact'
    | '/api/verify-recaptcha'
    | '/blog/$slug'
    | '/demo/better-auth'
    | '/demo/tanstack-form'
    | '/demo/tanstack-query'
    | '/en-US/$'
    | '/$lang/'
    | '/blog/'
    | '/en-US/'
    | '/api/auth/$'
    | '/demo/sentry/testing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/$lang/contact'
    | '/api/verify-recaptcha'
    | '/blog/$slug'
    | '/demo/better-auth'
    | '/demo/tanstack-form'
    | '/demo/tanstack-query'
    | '/en-US/$'
    | '/$lang'
    | '/blog'
    | '/en-US'
    | '/api/auth/$'
    | '/demo/sentry/testing'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/$lang/contact'
    | '/api/verify-recaptcha'
    | '/blog/$slug'
    | '/demo/better-auth'
    | '/demo/tanstack-form'
    | '/demo/tanstack-query'
    | '/en-US/$'
    | '/$lang/'
    | '/blog/'
    | '/en-US/'
    | '/api/auth/$'
    | '/demo/sentry/testing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  LangContactRoute: typeof LangContactRoute
  ApiVerifyRecaptchaRoute: typeof ApiVerifyRecaptchaRoute
  BlogSlugRoute: typeof BlogSlugRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoTanstackFormRoute: typeof DemoTanstackFormRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  EnUSSplatRoute: typeof EnUSSplatRoute
  LangIndexRoute: typeof LangIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  EnUSIndexRoute: typeof EnUSIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DemoSentryTestingRoute: typeof DemoSentryTestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en-US/': {
      id: '/en-US/'
      path: '/en-US'
      fullPath: '/en-US/'
      preLoaderRoute: typeof EnUSIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/$lang'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en-US/$': {
      id: '/en-US/$'
      path: '/en-US/$'
      fullPath: '/en-US/$'
      preLoaderRoute: typeof EnUSSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-form': {
      id: '/demo/tanstack-form'
      path: '/demo/tanstack-form'
      fullPath: '/demo/tanstack-form'
      preLoaderRoute: typeof DemoTanstackFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-recaptcha': {
      id: '/api/verify-recaptcha'
      path: '/api/verify-recaptcha'
      fullPath: '/api/verify-recaptcha'
      preLoaderRoute: typeof ApiVerifyRecaptchaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/contact': {
      id: '/$lang/contact'
      path: '/$lang/contact'
      fullPath: '/$lang/contact'
      preLoaderRoute: typeof LangContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/sentry/testing': {
      id: '/demo/sentry/testing'
      path: '/demo/sentry/testing'
      fullPath: '/demo/sentry/testing'
      preLoaderRoute: typeof DemoSentryTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  LangContactRoute: LangContactRoute,
  ApiVerifyRecaptchaRoute: ApiVerifyRecaptchaRoute,
  BlogSlugRoute: BlogSlugRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoTanstackFormRoute: DemoTanstackFormRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  EnUSSplatRoute: EnUSSplatRoute,
  LangIndexRoute: LangIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  EnUSIndexRoute: EnUSIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DemoSentryTestingRoute: DemoSentryTestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
